qlib_init:
    provider_uri: "~/.qlib/qlib_data/tw_data"
    region: tw
market: &market "all"
benchmark: &benchmark "2330.tw"
data_handler_config: &data_handler_config
    start_time: 2024-01-01
    end_time: 2025-08-07
    fit_start_time: 2024-01-01
    fit_end_time: 2024-08-31
    instruments: *market
    infer_processors:
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 30
            n_drop: 3
    backtest:
        start_time: 2024-09-01
        end_time: 2024-12-31
        account: 1000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.1
            deal_price: close
            open_cost: 0.001425
            close_cost: 0.001425
            min_cost: 20

task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.9
            learning_rate: 0.02
            subsample: 0.8
            lambda_l1: 100.0
            lambda_l2: 300.0
            max_depth: 6
            num_leaves: 120
            num_threads: 20
            min_data_in_leaf: 100
            feature_fraction: 0.8
            early_stopping_rounds: 100
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2024-01-01, 2024-08-31]
                valid: [2024-09-01, 2024-10-31]
                test: [2024-11-01, 2024-12-31]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
